SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  This is a dummy target
copyrights:
- Copyright (C) 2026 embedded brains GmbH & Co. KG
enabled-by: true
description:
  This describes the dummy target.
key: dummy
links:
- role: test-timeouts
  uid: dummy/test-timeouts
- role: performance-runtime-limits-provider
  uid: dummy/perf-default
name: Dummy Target
non-functional-type: design-target
rationale: null
references: []
requirement-type: non-functional
target-hash: cpI09Ju6orF2eoJcmJi4igeIarypsRNwUxTrZSs9LMg=
text: |
  The ${.:/name} shall be a ${/glossary/target:/term}.
type: requirement
